version: "3.8"
services:
  fashionpal-frontend:
    image: amulya365/fashionpal-frontend:latest
    container_name: fashionpal-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      amulaya_fashionpal:
        ipv4_address: 172.16.144.176

  fashionpal-backend:
    image: amulya365/fashionpal-backend:latest
    container_name: fashionpal-backend
    ports:
      - "5000:5000"
    networks:
      amulaya_fashionpal:
        ipv4_address: 172.16.144.177
    
    volumes:
      - ./backend/logs:/usr/src/app/logs/

networks:
  amulaya_fashionpal:
    external: true

