services:
  fashionpal-frontend:
    image: amulya365/fashionpal-frontend:latest
    container_name: fashionpal-frontend

    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      fashionpal:
        ipv4_address:  192.168.43.53 
  fashionpal-backend:
    image: amulya365/fashionpal-backend:latest
    container_name: fashionpal-backend
    ports:
      - "5000:5000"
    networks:
      fashionpal:
        ipv4_address: 192.168.43.54
    
    volumes:
      - ./backend/logs:/usr/src/app/logs/
networks:
  fashionpal:
    ipam:
      driver: default
      config:
      - subnet: 192.168.43.0/24